### ISSUE TITLE
Tracking: Threading + IO redesign

### ISSUE THREAD

**Issue by sinui0** [privacy-ethereum/mpz#112]
This is a tracking issue for the redesign work for how we model protocol execution and IO.

[Branch](https://github.com/privacy-scaling-explorations/mpz/tree/threading-refactor)

## Tasks

- [x] Introduce `mpz-common` which provides types and traits for threading and synchronization. It also adds [`serio`](https://github.com/tlsnotary/tlsn-utils/tree/dev/serio) for our IO abstraction. #107 
- [x] Encapsulate our coin-toss protocols async layer #108 
- [x] Update `mpz-ot` to use `mpz-common` and deprecate the KOS15 actor impl #109 
- [x] Finish implementing OT traits for KOS15 shared variant.
- [x] Implement a multi-threaded executor/context in `mpz-common`
- [x] Update `mpz-garble`
- [x] Update `mpz-share-conversion`
